
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("360x730")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 730,
    width = 360,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
   # command=lambda: OUTPUT_PATH / Path(r"assets\frame1"),                  ojo aqui cambios!!!
    relief="flat"
)
button_1.place(
    x=55.0,
    y=650.0,
    width=250.0,
    height=40.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    174.0,
    130.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    180.0,
    429.0,
    image=image_image_2
)

canvas.create_text(
    54.0,
    230.0,
    anchor="nw",
    text="¡BIENVENIDA!",
    fill="#147984",
    font=("RobotoRoman SemiBold", 40 * -1)
)

canvas.create_text(
    54.0,
    580.0,
    anchor="nw",
    text="¡BIENVENIDO!",
    fill="#147984",
    font=("RobotoRoman SemiBold", 40 * -1)
)
window.resizable(False, False)
window.mainloop()
